spring:
  application:
    name: service-producer-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}

server:
  port: 8080