server:
  port: 9002
  
spring:
  application:
    name: service-consumer-demo
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.int}